### ISSUE TITLE
"camera_image" shown instead of map image

### ISSUE THREAD

**Issue by travnick** [Jezza34000/homeassistant_weback_component#34]
### Device brand

RoboJet

### Device model

X-ONE

### Smartphone application

WeBack

### Component version

1.1.8

### HA core version

2024.5.4

### Describe the problem

Card shows `camera_image` text instead of valid map.
A `predefined_selections` values in second vard was autogenerated by the integration (or the lovelace plugin, not sure who is responsible)

![image](https://github.com/Jezza34000/homeassistant_weback_component/assets/619590/ea0ed3bc-30d5-413c-8dfb-e51b643d2d90)

Dashboard configuration:
```
views:
  - title: Home
    cards:
      - type: custom:config-template-card
        variables:
          ROOMS: states['camera.robot_map'].attributes.rooms
        entities:
          - camera.robot_map
        card:
          type: custom:xiaomi-vacuum-map-card
          map_source:
            camera: camera.robot_map
          calibration_source:
            camera: true
          entity: vacuum.robot
          vacuum_platform: send_command
          title: Vacuum
          preset_name: Live map
          map_modes:
            - template: vacuum_clean_zone
            - template: vacuum_clean_segment
              name: Rooms
              icon: mdi:floor-plan
              predefined_selections: ${ROOMS}
      - type: custom:xiaomi-vacuum-map-card
        map_source:
          camera: camera.robot_map
        calibration_source:
          camera: true
        entity: vacuum.robot
        vacuum_platform: send_command
        map_locked: false
        two_finger_pan: false
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_goto
          - template: vacuum_clean_segment
            predefined_selections:
              - id: '0'
                icon:
                  name: mdi:broom
                  x: 176
                  'y': -272
                label:
                  text: Room 0
                  x: 176
                  'y': -272
                  offset_y: 35
                outline:
                  - - 280
                    - -410
                  - - 290
                    - -400
                  - - 290
                    - -380
                  - - 300
                    - -370
                  - - 360
                    - -370
                  - - 370
                    - -360
                  - - 370
                    - -310
                  - - 380
                    - -300
                  - - 380
                    - -60
                  - - 360
                    - -50
                  - - 360
                    - 128
                  - - -410
                    - 131
                  - - -410
                    - -350
                  - - -390
                    - -370
                  - - 150
                    - -370
                  - - 160
                    - -380
                  - - 160
                    - -410
              - id: '1'
                icon:
                  name: mdi:broom
                  x: 700
                  'y': -306
                label:
                  text: Room 1
                  x: 700
                  'y': -306
                  offset_y: 35
                outline:
                  - - 560
                    - -470
                  - - 590
                    - -440
                  - - 600
                    - -440
                  - - 630
                    - -410
                  - - 640
                    - -410
                  - - 640
                    - -390
                  - - 670
                    - -370
                  - - 670
                    - -350
                  - - 680
                    - -340
                  - - 1070
                    - -340
                  - - 1080
                    - -320
                  - - 1080
                    - -290
                  - - 1090
                    - -280
                  - - 1090
                    - -240
                  - - 1110
                    - -210
                  - - 1110
                    - -180
                  - - 1090
                    - -160
                  - - 1090
                    - -140
                  - - 1080
                    - -130
                  - - 490
                    - -130
                  - - 480
                    - -140
                  - - 410
                    - -140
                  - - 390
                    - -150
                  - - 390
                    - -300
                  - - 410
                    - -300
                  - - 420
                    - -310
                  - - 420
                    - -370
                  - - 430
                    - -380
                  - - 470
                    - -380
                  - - 490
                    - -400
                  - - 490
                    - -420
                  - - 540
                    - -470
              - id: '2'
                icon:
                  name: mdi:broom
                  x: 659
                  'y': 249
                label:
                  text: Room 2
                  x: 659
                  'y': 249
                  offset_y: 35
                outline:
                  - - 1090
                    - -70
                  - - 1100
                    - -60
                  - - 1100
                    - 420
                  - - 1090
                    - 430
                  - - 760
                    - 430
                  - - 750
                    - 440
                  - - 750
                    - 520
                  - - 740
                    - 530
                  - - 560
                    - 530
                  - - 550
                    - 520
                  - - 540
                    - 520
                  - - 530
                    - 510
                  - - 530
                    - 140
                  - - 520
                    - 130
                  - - 430
                    - 130
                  - - 430
                    - 100
                  - - 420
                    - 90
                  - - 370
                    - 90
                  - - 370
                    - -50
                  - - 590
                    - -50
                  - - 610
                    - -70
              - id: '3'
                icon:
                  name: mdi:broom
                  x: 707
                  'y': -809
                label:
                  text: Room 3
                  x: 707
                  'y': -809
                  offset_y: 35
                outline:
                  - - 1200
                    - -1420
                  - - 1210
                    - -1410
                  - - 1210
                    - -1240
                  - - 1200
                    - -1230
                  - - 1200
                    - -450
                  - - 1190
                    - -440
                  - - 650
                    - -440
                  - - 640
                    - -430
                  - - 640
                    - -420
                  - - 630
                    - -420
                  - - 600
                    - -450
                  - - 590
                    - -450
                  - - 560
                    - -480
                  - - 540
                    - -480
                  - - 520
                    - -460
                  - - 470
                    - -460
                  - - 470
                    - -480
                  - - 430
                    - -520
                  - - 430
                    - -1340
                  - - 440
                    - -1350
                  - - 440
                    - -1410
                  - - 490
                    - -1410
                  - - 500
                    - -1420
              - id: '4'
                icon:
                  name: mdi:broom
                  x: -28
                  'y': -866
                label:
                  text: Room 4
                  x: -28
                  'y': -866
                  offset_y: 35
                outline:
                  - - -70
                    - -1430
                  - - -60
                    - -1420
                  - - 270
                    - -1420
                  - - 280
                    - -1410
                  - - 400
                    - -1410
                  - - 400
                    - -1370
                  - - 400
                    - -960
                  - - 390
                    - -950
                  - - 390
                    - -720
                  - - 380
                    - -710
                  - - 380
                    - -490
                  - - 360
                    - -430
                  - - 270
                    - -430
                  - - 260
                    - -420
                  - - 160
                    - -420
                  - - 150
                    - -440
                  - - -10
                    - -440
                  - - -20
                    - -450
                  - - -290
                    - -450
                  - - -300
                    - -460
                  - - -380
                    - -460
                  - - -410
                    - -470
                  - - -410
                    - -560
                  - - -400
                    - -570
                  - - -400
                    - -840
                  - - -390
                    - -850
                  - - -390
                    - -1070
                  - - -380
                    - -1080
                  - - -380
                    - -1360
                  - - -370
                    - -1370
                  - - -370
                    - -1420
                  - - -360
                    - -1430
              - id: '5'
                icon:
                  name: mdi:broom
                  x: -178
                  'y': 359
                label:
                  text: Room 5
                  x: -178
                  'y': 359
                  offset_y: 35
                outline:
                  - - 71
                    - 130
                  - - 75
                    - 480
                  - - 30
                    - 480
                  - - 10
                    - 500
                  - - -90
                    - 500
                  - - -110
                    - 480
                  - - -130
                    - 430
                  - - -200
                    - 360
                  - - -210
                    - 360
                  - - -230
                    - 340
                  - - -250
                    - 330
                  - - -270
                    - 330
                  - - -280
                    - 320
                  - - -310
                    - 320
                  - - -320
                    - 310
                  - - -410
                    - 310
                  - - -410
                    - 131
              - id: '6'
                icon:
                  name: mdi:broom
                  x: 254
                  'y': 355
                label:
                  text: Room 6
                  x: 254
                  'y': 355
                  offset_y: 35
                outline:
                  - - 71
                    - 130
                  - - 360
                    - 128
                  - - 360
                    - 450
                  - - 340
                    - 460
                  - - 320
                    - 480
                  - - 75
                    - 480
type: custom:config-template-card
```

### Home Assistant Logs

Overwhelming logs count, not sure what to send. As far as I can see there are only `DEBUG` entries, no `ERROR`, `WARNING` or even `INFO`.
